packages:
  - internal/*
  - packages/*
  - packages/core/base/*
  - apps/*
catalog:
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  vue: ^3.5.13
  vue-router: ^4.5.0
  vite: ^6.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^7.7.2
  unbuild: ^3.5.0
  pkg-types: ^2.1.0
