packages:
  - internal/*
  - packages/*
  - packages/core/base/*
  - apps/*
catalog:
  '@tailwindcss/vite': ^4.0.17
  '@types/node': ^22.13.10
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/coverage-v8': ^3.0.9
  '@vue/shared': ^3.5.13
  '@vueuse/core': ^13.0.0
  axios: ^1.8.4
  chalk: ^5.3.0
  defu: ^6.1.4
  expect-type: ^1.2.0
  happy-dom: ^17.4.4
  dotenv: ^16.4.7
  pinia-plugin-persistedstate: ^4.2.0
  pinia: ^3.0.1
  pkg-types: ^2.1.0
  tailwindcss: ^4.0.17
  turbo: ^2.5.4
  typescript: ^5.8.0
  unbuild: ^3.5.0
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^7.7.2
  vite: ^6.2.1
  vitepress: ^1.6.3
  vitest: ^3.0.9
  vue-router: ^4.5.0
  vue: ^3.5.13
  is-ci: ^4.1.0
  lefthook: ^1.12.0
  eslint: ^9.22.0
  bumpp: ^10.2.0
onlyBuiltDependencies:
  - esbuild
  - lefthook
