packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/core/base/*
  - apps/*
catalog:
  '@eslint/js': ^9.30.1
  '@tailwindcss/vite': ^4.0.17
  '@types/eslint': ^9.6.1
  '@types/node': ^22.13.10
  '@typescript-eslint/eslint-plugin': ^8.35.1
  '@typescript-eslint/parser': ^8.35.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/coverage-v8': ^3.0.9
  '@vue/shared': ^3.5.13
  '@vueuse/core': ^13.0.0
  axios: ^1.8.4
  bumpp: ^10.2.0
  chalk: ^5.3.0
  defu: ^6.1.4
  dotenv: ^16.4.7
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.20.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.2.0
  eslint: ^9.30.1
  expect-type: ^1.2.0
  globals: ^16.3.0
  jsonc-eslint-parser: ^2.4.0
  happy-dom: ^17.4.4
  is-ci: ^4.1.0
  lefthook: ^1.12.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.13
  pinia-plugin-persistedstate: ^4.2.0
  pinia: ^3.0.1
  pkg-types: ^2.1.0
  tailwindcss: ^4.0.17
  turbo: ^2.5.4
  typescript: ^5.8.0
  unbuild: ^3.5.0
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^7.7.2
  vite: ^6.2.1
  vitepress: ^1.6.3
  vitest: ^3.0.9
  vue-router: ^4.5.0
  vue: ^3.5.13
  vue-eslint-parser: ^10.2.0
onlyBuiltDependencies:
  - esbuild
  - lefthook
