packages:
  - internal/*
  - packages/*
  - packages/core/base/*
  - apps/*
catalog:
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vue/shared': ^3.5.13
  '@vueuse/core': ^13.0.0
  axios: ^1.8.4
  defu: ^6.1.4
  pinia: ^3.0.1
  pinia-plugin-persistedstate: ^4.2.0
  vue: ^3.5.13
  vue-router: ^4.5.0
  vite: ^6.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^7.7.2
  vitepress: ^1.6.3
  vitest: ^3.0.9
  unbuild: ^3.5.0
  pkg-types: ^2.1.0
  turbo: ^2.4.4
