name: Deploy

on:
    push:
        branches:
            - main
            - docs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
    packages: read

jobs:
    cache-and-install:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 9.5.0
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm i -w

            - name: Build docs
              run: pnpm docs:build

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./docs/.vitepress/dist"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
